import Navbar from "./Navbar";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <div className="content">
      <Head>
        <title>Next.js Role Based Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
      <footer>© 2022 Weiny Marchelina</footer>
    </div>
  );
};

export default Layout;
